### ISSUE TITLE
CPU to emulate with QEMU

### ISSUE THREAD

**Issue by Leunam5** [M0Rf30/qemu-kernels-rpi-arch-arm#1]
hello
I would like to know which CPU I use to emulate with QEMU, I'm using the following command but the emulation does not start
`qemu-system-arm -kernel qemu-kernel-4.9.60-aarch64 -cpu arm1176 -m 256 -machine vexpress-a9 -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw" -hda 2017-08-16-raspbian-stretch.img
`
thank you

**Comment by M0Rf30** [comment]
try to use this:
```qemu-system-arm -kernel qemu-kernel-4.9.60-aarch64 -cpu cortex-a53 -m 256 -M vexpress-a15 -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw" -hda 2017-08-16-raspbian-stretch.img -dtb vexpress-v2p-ca15-tc1.dtb```
or take a look here 

[simonpi](https://github.com/M0Rf30/simonpi)
